services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ${USERPROFILE}/.ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODEL=${model}
      - NVIDIA_VISIBLE_DEVICES=all
    command: ["serve"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  ruimbot:
    image: yawpets/ruimbot:latest
    pull_policy: always
    container_name: ruimbot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      model: ${model}
    volumes:
      - ${RUIM_DATA_DIR}:/app/data
